#!/bin/bash

# https://docs.docker.com/docker-hub/builds/advanced/
# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKER_REPO: the name of the Docker repository being built.
# DOCKERFILE_PATH: the dockerfile currently being built.
# DOCKER_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)

set -e
set -x
set -u

ANSIBLE_LINT_VERSION=$(grep ansible-lint requirements.txt | cut -f 3 -d " ")

docker tag ${IMAGE_NAME} ${DOCKER_REPO}:v${ANSIBLE_LINT_VERSION}
docker push ${DOCKER_REPO}:v${ANSIBLE_LINT_VERSION}
